### ISSUE TITLE
Retrieve credentials from environment variable  HAKAI_API_TOKEN

### ISSUE THREAD

**Issue by JessyBarrette** [HakaiInstitute/hakai-api-client-py#6]
It's all in the title.
@tayden any thoughts? I can make a quick PR to include that

**Comment by tayden** [comment]
Seem reasonable to me. Would the value be the string you copy from https://hecate.hakai.org/api-client-login, or just the "token" parameter from that string?

Each option has some upsides and downsides

**Comment by JessyBarrette** [comment]
I feel like the string form  https://hecate.hakai.org/api-client-login is the simplest
